services:
  catur-portofolio-web:
    container_name: catur-portofolio-web
    platform: linux/amd64
    image: ghcr.io/caturbgs/catur-portofolio-web:latest
    env_file:
      - .env
    # Environment variables will be loaded from .env file
    # You can still override specific variables here if needed
    # environment:
    #   - NUXT_PUBLIC_API_BASE=/api/new
    restart: unless-stopped
    ports:
      - "3000:3000"
    # resources limitation
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 128M
