name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a version

      - name: Install dependencies
        run: bun install

      - name: Generate static site
        run: bun run generate

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact-dir: .output/public # Ensure this matches your dist directory
          token: ${{ secrets.GITHUB_TOKEN }}
